#!/usr/bin/env python

#    Copyright (C) 2008 Dirk Vanden Boer <dirk.vdb@gmail.com>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

import gtk
import gobject
import locale
import gettext
import os
import sys
import dbus

from phonetooth import mainwindow

APP_NAME = 'phonetooth'

def main():
    setLocale()

    gobject.threads_init()
    gtk.gdk.threads_init()
    dbus.glib.init_threads()

    mainWindow = mainwindow.MainWindow()
    gtk.main()

def setLocale():
    installed = True

    #detect if we are running from local copy
    try:
        from phonetooth import constants
    except ImportError:
        installed = False

    try:
        locale.setlocale(locale.LC_ALL, '')
        gettext.textdomain(APP_NAME)
        gtk.glade.textdomain(APP_NAME)

        if installed == False:
            gettext.bindtextdomain(APP_NAME, 'locale')
            gtk.glade.bindtextdomain(APP_NAME, 'locale')
    except:
        pass


if __name__ == "__main__":
    main()



