#!/usr/bin/env python
import time
import sys
import socket
import bluetooth

import gtk
import gtk.glade

from pyphonetooth import mainwindow
from pyphonetooth import mobilephone

def main():
    mainWindow = mainwindow.MainWindow()
    gtk.main()

if __name__ == "__main__":
    main()



